### ISSUE TITLE
Prepare demands needs to write csv and not json

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO_API#1]
The [current script](https://github.com/USEPA/USEEIO_API/blob/master/scripts/prepare_demands.py) is writing json and instead needs to write csv to be compliant with the API

**Comment by WesIngwersen** [comment]
Should this script not be a part of the iomb since other model data writing is part of the iomb?

**Comment by msrocka** [comment]
I updated the script with the last version that I used to create the files for the API: the list with the meta data of the demand vectors `demands.csv` and the single demand vectors as JSON files in the
`<model>/demands` folder.

`iomb` could be a better place for this script but demand vectors are currently also not stored in an `iomb` model. Maybe the [USEEIO](https://github.com/USEPA/USEEIO) repository would be a good place for this script and the data of the demand vectors.

**Comment by WesIngwersen** [comment]
I agree with moving it. I moved it to the iomb in the scripts folder.
