### ISSUE TITLE
Mismatch of U length to sector length in USEEIOv2.0.1-411 model

### ISSUE THREAD

**Issue by cantide5ga** [USEPA/USEEIO_API#32]
The Life Cycle Impacts per Dollar, [46] in the Jupyter notebook, is erroring out. The reason looks to be because `https://api.edap-cluster.com/USEEIOv2.0.1-411/matrix/U?row=0` call returns 20 more indexes than there are sectors. Is this expected?

**Comment by WesIngwersen** [comment]
Good find. The change in nomenclature in USEEIO models may be a cause of confusion.   I see that this code in the notebook example was not updated with this change. 

 What is now `N` in the API and useeior models used to be called `U`.  The `U` matrix is now the Use table used to build the model, but not part of the model results. The Use table is composed of industries and final demand...[see the format docs](https://github.com/USEPA/useeior/blob/master/format_specs/Model.md#U) so it has different rows and columns.

**Comment by cantide5ga** [comment]
Excellent, think I got this right: https://github.com/USEPA/USEEIO_API/pull/38

Also sneaked in another fix.

Thanks!
