### ISSUE TITLE
Document building docker image in main README

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO_API#5]

**Comment by msrocka** [comment]
not sure where to put this in the Wiki now, but here is a proposal for documenting this

## Building a Docker image

The repository contains a simple `Dockerfile` which can be used to build a Docker image:

```Dockerfile
FROM scratch

COPY useeio_api /opt/useeio_api
WORKDIR /opt/useeio_api

EXPOSE 8080

CMD [ "./app", "-port", "8080"]
```

It expects that the API binary is saved in a file `app` that is located in a folder `useeio_api` next to the folders `data` and `static` that contain the API data and the static pages that should be hosted together with the API:

```
- useeio_api/
  +-- data/
  +-- static/
  - app
- Dockerfile
```

In this folder, you can then run the `docker build` command to build the image, e.g.:

```bash
docker build -t useeio_api .
```

This will store the image under `useeio_api` and you should be able to run it via the following command (`-p 8080:8080` maps the port `8080` of the docker container to the port `8080` of the host system):

```bash
docker run -p 8080:8080 useeio_api
```

To export the image as tar file, run

```bash
docker save -o export.file.name.tar
```

**Comment by WesIngwersen** [comment]
Added to the Wiki under 'Deploy'.  As I understand it only applies to the Go version of the API and not the Python version.
